FROM eclipse-temurin:21-jdk
LABEL "org.opencontainers.image.authors"="BankingMangementSystem"
COPY target/card-0.0.1-SNAPSHOT.jar card-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","card-0.0.1-SNAPSHOT.jar"]