sonar.projectKey=smartcourier-microservices
sonar.projectName=SmartCourier Microservices
sonar.projectVersion=1.0.0

sonar.sources=auth-service/src/main/java,delivery-service/src/main/java,tracking-service/src/main/java,admin-service/src/main/java,api-gateway/src/main/java,config-server/src/main/java,eureka-server/src/main/java
sonar.tests=auth-service/src/test/java,delivery-service/src/test/java,tracking-service/src/test/java,admin-service/src/test/java,api-gateway/src/test/java,config-server/src/test/java,eureka-server/src/test/java

sonar.java.binaries=auth-service/target/classes,delivery-service/target/classes,tracking-service/target/classes,admin-service/target/classes,api-gateway/target/classes,config-server/target/classes,eureka-server/target/classes
sonar.exclusions=**/target/**,**/.mvn/**,**/mvnw,**/mvnw.cmd,**/.idea/**
sonar.coverage.exclusions=**/config/**,**/*Application.java

sonar.sourceEncoding=UTF-8
