package com.cap.springDto.controller;

import com.cap.springDto.dto.ApiResponse;
import com.cap.springDto.dto.StudentRequestDto;
import com.cap.springDto.dto.StudentResponseDto;
import com.cap.springDto.service.IStudentService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/*
 * StudentController
 *
 * This controller handles HTTP requests related to Student operations.
 * It follows REST standards and communicates with the Service layer.
 *
 * Flow:
 * Controller -> Service -> Repository -> Database
 */

@RestController
@RequestMapping("/students")
@RequiredArgsConstructor
public class StudentController {

    // Injecting service layer using constructor injection
    private final IStudentService studentService;

    /*
     * Create a new student
     *
     * Endpoint: POST /students
     * Request Body: StudentRequestDto
     * Response: ApiResponse<StudentResponseDto>
     */
    @PostMapping
    public ResponseEntity<ApiResponse<StudentResponseDto>> saveStudent(
            @Valid @RequestBody StudentRequestDto dto) {

        StudentResponseDto responseDto = studentService.saveStudent(dto);

        ApiResponse<StudentResponseDto> apiResponse =
                new ApiResponse<>(201, "Student created successfully", responseDto);

        return ResponseEntity.status(HttpStatus.CREATED).body(apiResponse);
    }

    /*
     * Get student by ID
     *
     * Endpoint: GET /students/{id}
     * Path Variable: id
     * Response: ApiResponse<StudentResponseDto>
     */
    @GetMapping("get-by-id/{id}")
    public ResponseEntity<ApiResponse<StudentResponseDto>> getStudentById(
            @PathVariable Integer id) {

        StudentResponseDto responseDto = studentService.getStudentById(id);

        ApiResponse<StudentResponseDto> apiResponse =
                new ApiResponse<>(200, "Student fetched successfully", responseDto);

        return ResponseEntity.ok(apiResponse);
    }

    /*
     * Get all students
     *
     * Endpoint: GET /students
     * Response: ApiResponse<List<StudentResponseDto>>
     */
    @GetMapping("/get-all")
    public ResponseEntity<ApiResponse<List<StudentResponseDto>>> getAllStudents() {

        List<StudentResponseDto> students = studentService.getAllStudents();

        ApiResponse<List<StudentResponseDto>> apiResponse =
                new ApiResponse<>(200, "Students fetched successfully", students);

        return ResponseEntity.ok(apiResponse);
    }

    /*
     * Delete student by ID
     *
     * Endpoint: DELETE /students/{id}
     * Path Variable: id
     * Response: ApiResponse<Void>
     */
    @DeleteMapping("delete/{id}")
    public ResponseEntity<ApiResponse<Void>> deleteStudentById(
            @PathVariable Integer id) {

        studentService.deleteStudentById(id);

        ApiResponse<Void> apiResponse =
                new ApiResponse<>(200, "Student deleted successfully", null);

        return ResponseEntity.ok(apiResponse);
    }
}
//        id is autogenerated so no need to create it ---- even in postman ----- post http://localhost:8080/students
