FROM eclipse-temurin:21-jdk
LABEL "org.opencontainers.image.authors"="BankingMangementSystem"
COPY target/loan-0.0.1-SNAPSHOT.jar loan-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","loan-0.0.1-SNAPSHOT.jar"]